GET http://localhost:3001/api/backlogItems

###
GET http://localhost:3001/api/backlogItems/g

###
POST http://localhost:3001/api/backlogItems
Content-Type: application/json

{
  "title": "test",
  "format": "Movie",
  "completionStatus": "Backlog"
}

###
DELETE http://localhost:3001/api/backlogItems/g

###
PUT http://localhost:3001/api/backlogItems/g
Content-Type: application/json

{
  "title": "test",
  "format": "Movie",
  "completionStatus": "Complete"
}