GET http://localhost:3001/api/backlogItems

###
GET http://localhost:3001/api/backlogItems/g

###
POST http://localhost:3001/api/backlogItems
Content-Type: application/json

{
  "title": "test",
  "format": "Movie",
  "completionStatus": "Backlog"
}

###
DELETE http://localhost:3001/api/backlogItems/655d0e349645230f6787ccc8

###
PUT http://localhost:3001/api/backlogItems/655d10390243a11a365fc937
Content-Type: application/json

{
  "title": "test",
  "format": "Movie",
  "completionStatus": "Backlog"
}